apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server
  namespace: gameoflife
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
      - name: socket-server
        image: gameoflife/socket-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        resources:
          requests:
            memory: "2Gi" 
            cpu: "1000m" 
          limits:
            memory: "4Gi" 
            cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: socket-server
  namespace: gameoflife
spec:
  selector:
    app: socket-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort

